[workspace]
resolver = "2"

members = ["crates/goliath_backend", "crates/goliath_client", "crates/goliath_common", "crates/goliath_vehicle"]
default-members = ["crates/goliath_backend", "crates/goliath_client", "crates/goliath_common", "crates/goliath_vehicle"]
